<#
  Challenge 0 — provision the Foundry CLM microhack resources and write .env (Windows).
  Usage:   ./scripts/deploy.ps1 [-WithSql]
  Requires: az CLI (az login), rights to deploy GPT + Anthropic Claude models.
  The bash script (scripts/deploy.sh) is the primary path for Codespaces.
#>
param([switch]$WithSql)
$ErrorActionPreference = "Stop"

$Location    = $env:LOCATION    ?? "swedencentral"
$Suffix      = $env:SUFFIX      ?? -join ((48..57) + (97..122) | Get-Random -Count 5 | ForEach-Object {[char]$_})
$Rg          = $env:RG          ?? "rg-clm-microhack"
$Foundry     = $env:FOUNDRY     ?? "clmfoundry$Suffix"
$Project     = $env:PROJECT     ?? "clm-project"
$Search      = $env:SEARCH      ?? "clmsearch$Suffix"
$Storage     = $env:STORAGE     ?? "clmstor$Suffix"
$AppInsights = "clm-appinsights"

$GptOrch = "gpt-4.1"; $GptMini = "gpt-4o-mini"; $Claude = "claude-sonnet-4-5"

Write-Host "▶ Resource group: $Rg ($Location); Foundry $Foundry / project $Project"

az group create -n $Rg -l $Location -o none

az cognitiveservices account create -n $Foundry -g $Rg -l $Location `
  --kind AIServices --sku S0 --custom-domain $Foundry --yes -o none
Write-Host "  ✓ Foundry account created"

az cognitiveservices account project create --account-name $Foundry -g $Rg --project-name $Project -o none 2>$null `
  ; if ($LASTEXITCODE -ne 0) { Write-Host "  ! Create project '$Project' in the portal, then re-run." }

function Deploy-Model($name, $model, $version, $format, $cap) {
  Write-Host "  → deploying $name ($format $model v$version)"
  az cognitiveservices account deployment create -n $Foundry -g $Rg `
    --deployment-name $name --model-name $model --model-version $version --model-format $format `
    --sku-name GlobalStandard --sku-capacity $cap -o none 2>$null
  if ($LASTEXITCODE -ne 0) { Write-Host "    ! $name failed — check availability in $Location." }
}
Deploy-Model $GptOrch "gpt-4.1"          "2025-04-14" "OpenAI"    30
Deploy-Model $GptMini "gpt-4o-mini"      "2024-07-18" "OpenAI"    30
Deploy-Model $Claude  "claude-sonnet-4-5" "2"         "Anthropic" 20

az search service create -n $Search -g $Rg -l $Location --sku basic --partition-count 1 --replica-count 1 -o none
Write-Host "  ✓ Azure AI Search created"

az storage account create -n $Storage -g $Rg -l $Location --sku Standard_LRS -o none
$StorageConn = az storage account show-connection-string -n $Storage -g $Rg -o tsv
az storage container create --name clm-corpus --connection-string $StorageConn -o none
Write-Host "  ✓ Storage + container created"

az monitor app-insights component create --app $AppInsights -g $Rg -l $Location --kind web -o none
$AppInsightsConn = az monitor app-insights component show --app $AppInsights -g $Rg --query connectionString -o tsv
Write-Host "  ✓ Application Insights created"

$SqlConn = ""
if ($WithSql) {
  $SqlServer = "clmsql$Suffix"; $SqlDb = "clmdb"; $SqlPwd = "Clm!" + [System.Guid]::NewGuid().ToString("N").Substring(0,12)
  az sql server create -n $SqlServer -g $Rg -l $Location --admin-user clmadmin --admin-password $SqlPwd -o none
  az sql db create -s $SqlServer -g $Rg -n $SqlDb --service-objective Basic -o none
  az sql server firewall-rule create -s $SqlServer -g $Rg -n AllowAzure --start-ip-address 0.0.0.0 --end-ip-address 0.0.0.0 -o none
  $SqlConn = "Driver={ODBC Driver 18 for SQL Server};Server=tcp:$SqlServer.database.windows.net,1433;Database=$SqlDb;Uid=clmadmin;Pwd=$SqlPwd;Encrypt=yes;TrustServerCertificate=no;"
  Write-Host "  ✓ Azure SQL created"
} else {
  Write-Host "  · Skipping Azure SQL (-WithSql to provision). Tool falls back to challenge-0/data/contracts_seed.json."
}

$ProjectEndpoint = "https://$Foundry.services.ai.azure.com/api/projects/$Project"
$SearchEndpoint  = "https://$Search.search.windows.net"

@"
# Autogenerated by scripts/deploy.ps1 — do not commit.
AZURE_AI_PROJECT_ENDPOINT=$ProjectEndpoint

MODEL_ORCHESTRATOR=$GptOrch
MODEL_DRAFTING=$Claude
MODEL_CLAUSE_RISK=$Claude
MODEL_RENEWAL=$GptMini

AZURE_SEARCH_ENDPOINT=$SearchEndpoint
AZURE_SEARCH_INDEX=clm-corpus
AZURE_SEARCH_CONNECTION_NAME=clm-search

AZURE_STORAGE_CONNECTION_STRING=$StorageConn
AZURE_STORAGE_CONTAINER=clm-corpus

APPLICATIONINSIGHTS_CONNECTION_STRING=$AppInsightsConn
AZURE_TRACING_GEN_AI_CONTENT_RECORDING_ENABLED=true

AZURE_SQL_CONNECTION_STRING=$SqlConn

MICROSOFT_APP_ID=
MICROSOFT_APP_PASSWORD=
MICROSOFT_APP_TENANT_ID=
TEAMS_SERVICE_URL=
TEAMS_CONVERSATION_ID=
"@ | Out-File -FilePath ".env" -Encoding utf8

Write-Host "`n✅ Deployment complete. Wrote .env. Next: python scripts/seed_corpus.py; python scripts/smoke_test.py"
