#!/usr/bin/env python3
"""Write the repo-root .env from azd (Bicep) outputs.

Runs as the azd `postprovision` hook (see azure.yaml). Reads the provisioned
values via `azd env get-values` and writes a .env identical in shape to the one
scripts/deploy.sh produces, so every challenge works whether you provisioned
with `azd up` or the bash/PowerShell script.
"""
from __future__ import annotations

import subprocess
import sys
from pathlib import Path

REPO_ROOT = Path(__file__).resolve().parents[1]
ENV_PATH = REPO_ROOT / ".env"

# Keys sourced from Bicep outputs (via azd env). Fall back to the .env.example
# defaults for the constant-valued ones if an output is missing.
DEFAULTS = {
    "MODEL_ORCHESTRATOR": "gpt-4.1",
    "MODEL_DRAFTING": "claude-sonnet-4-5",
    "MODEL_CLAUSE_RISK": "claude-sonnet-4-5",
    "MODEL_RENEWAL": "gpt-4o-mini",
    "AZURE_SEARCH_INDEX": "clm-corpus",
    "AZURE_SEARCH_CONNECTION_NAME": "clm-search",
    "AZURE_STORAGE_CONTAINER": "clm-corpus",
    "AZURE_TRACING_GEN_AI_CONTENT_RECORDING_ENABLED": "true",
}


def azd_env_values() -> dict[str, str]:
    """Return azd environment values as a dict (parsing KEY="value" lines)."""
    try:
        proc = subprocess.run(
            ["azd", "env", "get-values"],
            cwd=REPO_ROOT,
            capture_output=True,
            text=True,
            check=True,
        )
    except FileNotFoundError:
        sys.exit("✗ azd not found on PATH. Run this hook via `azd up`/`azd provision`.")
    except subprocess.CalledProcessError as exc:
        sys.exit(f"✗ `azd env get-values` failed:\n{exc.stderr}")

    values: dict[str, str] = {}
    for line in proc.stdout.splitlines():
        line = line.strip()
        if not line or "=" not in line:
            continue
        key, _, val = line.partition("=")
        values[key.strip()] = val.strip().strip('"')
    return values


def main() -> None:
    env = azd_env_values()

    def get(key: str) -> str:
        return env.get(key) or DEFAULTS.get(key, "")

    content = f"""# Autogenerated by scripts/write_env.py (azd postprovision) — do not commit.
AZURE_AI_PROJECT_ENDPOINT={get("AZURE_AI_PROJECT_ENDPOINT")}

MODEL_ORCHESTRATOR={get("MODEL_ORCHESTRATOR")}
MODEL_DRAFTING={get("MODEL_DRAFTING")}
MODEL_CLAUSE_RISK={get("MODEL_CLAUSE_RISK")}
MODEL_RENEWAL={get("MODEL_RENEWAL")}

AZURE_SEARCH_ENDPOINT={get("AZURE_SEARCH_ENDPOINT")}
AZURE_SEARCH_INDEX={get("AZURE_SEARCH_INDEX")}
AZURE_SEARCH_CONNECTION_NAME={get("AZURE_SEARCH_CONNECTION_NAME")}

AZURE_STORAGE_CONNECTION_STRING={get("AZURE_STORAGE_CONNECTION_STRING")}
AZURE_STORAGE_CONTAINER={get("AZURE_STORAGE_CONTAINER")}

APPLICATIONINSIGHTS_CONNECTION_STRING={get("APPLICATIONINSIGHTS_CONNECTION_STRING")}
AZURE_TRACING_GEN_AI_CONTENT_RECORDING_ENABLED={get("AZURE_TRACING_GEN_AI_CONTENT_RECORDING_ENABLED")}

AZURE_SQL_CONNECTION_STRING={get("AZURE_SQL_CONNECTION_STRING")}

MICROSOFT_APP_ID=
MICROSOFT_APP_PASSWORD=
MICROSOFT_APP_TENANT_ID=
TEAMS_SERVICE_URL=
TEAMS_CONVERSATION_ID=
"""

    ENV_PATH.write_text(content, encoding="utf-8")
    print(f"✓ Wrote {ENV_PATH}")
    if not get("AZURE_AI_PROJECT_ENDPOINT"):
        print("  ! AZURE_AI_PROJECT_ENDPOINT is empty — check the deployment outputs.")
    print("  Next: python scripts/seed_corpus.py && python scripts/smoke_test.py")


if __name__ == "__main__":
    main()
